# Generated by Django 5.2.9 on 2025-12-05 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('Weight', 'Weight'), ('BMI', 'BMI'), ('Blood Pressure', 'Blood Pressure'), ('Heart Rate', 'Heart Rate'), ('Blood Sugar', 'Blood Sugar'), ('Other', 'Other')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
