# Generated by Django 5.2.9 on 2025-12-05 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_calorieentry_id_alter_meal_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='condition',
            field=models.CharField(choices=[('PCOD', 'PCOD'), ('Fertility', 'Fertility'), ('General', 'General'), ('Hormonal', 'Hormonal'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('diabetes', 'Diabetes'), ('healthy', 'Healthy')], default='General', max_length=50),
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('weight_gain', 'Weight Gain'), ('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealplans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField(default=1)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.meal')),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.mealplan')),
            ],
        ),
    ]
