# Generated by Django 6.0 on 2025-12-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_managers_alter_user_id'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_app.user',),
        ),
    ]
